
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Feb 14 10:30:53 MST 2014
//----------------------------------------------------

package parser;

/** CUP generated interface containing symbol constants. */
public interface MataSym {
  /* terminals */
  public static final int DIVIDE = 12;
  public static final int CBRACE = 30;
  public static final int GE = 16;
  public static final int UMINUS = 14;
  public static final int INT = 4;
  public static final int ARRAY = 35;
  public static final int FOR = 34;
  public static final int MINUS = 10;
  public static final int OBRACE = 29;
  public static final int CBRAK = 26;
  public static final int NOT = 23;
  public static final int SEMICOLON = 7;
  public static final int AND = 21;
  public static final int LT = 17;
  public static final int TYPE = 3;
  public static final int OR = 22;
  public static final int PLUS = 9;
  public static final int ASSIGN = 24;
  public static final int IF = 31;
  public static final int DEFDIMENSION = 38;
  public static final int ID = 2;
  public static final int LE = 18;
  public static final int EOF = 0;
  public static final int RETURN = 36;
  public static final int CPAREN = 28;
  public static final int error = 1;
  public static final int MOD = 13;
  public static final int NEQ = 19;
  public static final int EQ = 20;
  public static final int REAL = 5;
  public static final int TIMES = 11;
  public static final int BOOLE = 6;
  public static final int COLON = 8;
  public static final int ELSE = 32;
  public static final int OPAREN = 27;
  public static final int WHILE = 33;
  public static final int DEFRADIUS = 39;
  public static final int DEFSTATES = 37;
  public static final int GT = 15;
  public static final int OBRAK = 25;
}

